---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
  labels:
    app: registry
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
              cpu: 100m
          ports:
            - containerPort: 5000
              name: docker-registry
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-data
          nfs:
            server: 192.168.1.10
            path: /volume1/k8s/docker-registry
