---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: docker-registry
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      # targetPort: 54320
      #30000-32767
      nodePort: 30100
  selector:
    app: docker-registry
